{{- if .Values.global.certman.deployacmeclusterissuer }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "A valid .Values.certman.email entry required! (either within the master chart global values or within the cert-manager sub-chart" .Values.certman.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
{{- end }}