---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ printf "%s-socops" (include "authelia.fullname" .) }}
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: {{ printf "http://%s.%s.svc.cluster.local/api/verify" (include "authelia.fullname" .) (.Release.Namespace) }}
    nginx.ingress.kubernetes.io/auth-signin: "https://login.awesomekbs.com/#/"
spec:
  tls:
  - secretName: socops-tls
    hosts:
    - socops.awesomekbs.com
  rules:
  - host: socops.awesomekbs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ printf "%s-%s" (.Release.Name) "nginx" }}
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ printf "%s-login" (include "authelia.fullname" .) }}
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
spec:
  tls:
  - secretName: authelia-login-tls
    hosts:
    - login.awesomekbs.com
  rules:
  - host: login.awesomekbs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ printf "%s-%s" (.Release.Name) "authelia" }}
          servicePort: {{ .Values.service.serviceport }}
