---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ template "authelia.fullname" . }}
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: {{ printf "http://%s.%s.svc.cluster.local/api/verify" (template "authelia.fullname" .) (.Release.Namespace) }}
    nginx.ingress.kubernetes.io/auth-signin: "https://login.eideon.com/#/"
spec:
  tls:
  - secretName: authelia-tls
    hosts:
    - login.eideon.com
    - socops.eideon.com
  rules:
  - host: login.eideon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: authelia-service
          servicePort: {{ .Values.service.serviceport }}
  - host: socops.eideon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ printf "%s-%s" (.Release.Name) "phpldapadmin" }}
          servicePort: 1443
