ApiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: authelia-tls
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ .Files.Get "certs/tls.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "certs/tls.key" | b64enc }}