---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: authelia-login-tls
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ .Files.Get "files/certs/login.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "files/certs/login.key" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "authelia.name" . }}
    chart: {{ template "authelia.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: socops-tls
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ .Files.Get "files/certs/socops.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "files/certs/socops.key" | b64enc }}

    