---
apiVersion: v1
kind: Service
metadata:
  name: authelia-service
spec:
  selector:
    app: authelia
  ports:
  - protocol: TCP
    port: {{ .Values.service.serviceport }}
    targetPort: {{ .Values.service.containerport }}
    name: authelia-port