{{- if .Values.genpass -}}
{{- range $secret := .Values.passwords.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    app: {{ template "socops.name" . }}
    chart: {{ template "socops.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- range $key, $val := .Values.keys -}}
  {{ $key }}: {{ template "socops.genpass" . }}
{{- end -}}
{{- end -}}
{{- end -}}