{{- if .Values.genpass -}}
{{- range $secret := .Values.passwords.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-creds" $.Release.Name $secret.name }}
  labels:
    app: {{ template "socops.name" $ }}
    chart: {{ template "socops.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- range $key, $val := $secret.keys }}
  {{ $key }}: {{ template "socops.genpass" . }}
  {{- end }}
---
{{- end }}
{{- end -}}